server:
  port: 8001

#mybatis
mybatis:
  type-aliases-package: com.lzw.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123


#日志配置
#logging:
#  file:
#    path: /log
#  level: debug





